apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-argo-example
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/your-username/flask-argo-example.git
    targetRevision: main
    path: k8s
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
