apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-argo-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-argo-example
  template:
    metadata:
      labels:
        app: flask-argo-example
    spec:
      containers:
      - name: flask-argo-example
        image: ghcr.io/dfratte/flask-argo-example:latest  # Image from GitHub Container Registry
        ports:
        - containerPort: 5000
        workingDir: /app  # Ensure the working directory is set to where app.py is located
        command: ["python"]  # Specify the Python command to run
        args: ["app.py"]  # Specify the path to the app.py file
      imagePullSecrets:
        - name: ghcr-secret  # Reference to the secret for pulling from GitHub Container Registry
