name: ci

on:
  push:
    branches:
      - main  # Trigger workflow on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger workflow on pull request to the 'main' branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Use a GitHub-hosted runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the code from the repository

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest

    - name: Run tests
      run: pytest tests/

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1  # Set up Buildx for multi-platform builds

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        username: ${{ github.actor }}  # GitHub username
        password: ${{ secrets.GITHUB_TOKEN }}  # GitHub token to authenticate

    - name: Build and Push Docker Image to GHCR
      run: |
        # Define the image name with the GitHub Container Registry (GHCR) URL
        IMAGE_NAME=ghcr.io/${{ github.repository }}/flask-argo-example:latest
        docker build -t $IMAGE_NAME .  # Build the Docker image
        docker push $IMAGE_NAME  # Push the image to GHCR
