name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest

    - name: Run tests
      run: pytest tests/

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1  # Set up Buildx for multi-platform builds

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}  # Use GitHub username
        password: ${{ secrets.GHCR_TOKEN }}  # Use GitHub token

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/flask-argo-example:latest .

    - name: Push Docker image to GitHub Container Registry
      run: |
        docker push ghcr.io/${{ github.repository }}/flask-argo-example:latest
